[package]
name = "flop_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
bigdecimal = "0.4"
clap = { version = "4.5", features = ["derive"] }
num-bigint = "0.4"
num-rational = "0.4"
num-traits = "0.2"
thiserror = "1.0"
